### ISSUE TITLE
Error 404 first time you open it after switching user

### ISSUE THREAD

**Issue by ariasuni** [YunoHost-Apps/freshrss_ynh#33]
If I use FreshRSS with a user, logout and login with another user, when the first time I open FreshRSS (for example `https://example.com/rss/`) I get a 404 error (on `https://example.com/rss/i/?c=error`). Afterwards (reloading or loading any other page of the app), it works perfectly fine.

**Comment by Alkarex** [comment]
@plopoyop Let me know when one of you find out whether this is a Yunohost or FreshRSS issue

**Comment by plopoyop** [comment]
@Alkarex There is a small problem with how FreshRSS deals with sessions where auth_type is http_auth. When we switch user, FreshRSS use the same session so, there is an error.

I see two possibilities : invalidate the session where the remote user username is different from the one contained into the session. Or have the username contained into the session name :
The bug is absent when I changed the init this way : 

`Minz_Session::init('FreshRSS-'. $_SERVER['REMOTE_USER']);`

**Comment by Alkarex** [comment]
@plopoyop Interesting :-) I will fix. How do you switch user using `http_auth` without restarting the browser?

**Comment by plopoyop** [comment]
@Alkarex good question.
Maybe you can try using httpie or trying to pass the user and password into the url.

**Comment by Alkarex** [comment]
Yes, I can of course send whatever headers from my side, but I am curious on how you produced this error from a normal browser. In the initial bug report, isn't it using the `form` login method? There is no option to log out when using `http_auth`.

**Comment by plopoyop** [comment]
In fact ynh provide a single sign on portal. 
You can logout/login in ynh and it will change your http auth without closing the browser

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1756
Tests welcome

**Comment by plopoyop** [comment]
fixed
